### ISSUE TITLE
不好意思，想请教一下跑代码的参数上的问题

### ISSUE THREAD

**Issue by xyc0833** [MarcusNerva/HMN#13]
在跑代码时：
![image](https://user-images.githubusercontent.com/57979311/200166606-bdb84f62-6d4d-44e2-b5ab-88dac4c39e42.png)

问题1 ：language_dir这个参数不对 ，想请教一下应该怎么设置
![image](https://user-images.githubusercontent.com/57979311/200166541-bb89561c-34e8-4e3a-a5f0-2b653ce1cbd5.png)
无法识别的参数 目录结构里面需要设置什么吗？
问题2  这个对应文件的数据集是不是应该放外面 ？谢谢
![image](https://user-images.githubusercontent.com/57979311/200166505-b8f23ccb-222a-43c5-a7fd-e192a3df47cc.png)

**Comment by yangxingrui** [comment]
--language_dir_name language --language_package_name vid2language_old是多余的，删掉这两个参数会对你有帮助

**Comment by xyc0833** [comment]
看到了  解决了问题 感恩感谢 杨同学

**Comment by tjumc** [comment]
您好，请问您能否把作者分享的预处理文件发给我一份？因为作者提供的链接已经失效了，我的邮箱是：chongma@email.ncu.edu.cn
