### ISSUE TITLE
提取特征的Faster-RCNN可以分享出来吗

### ISSUE THREAD

**Issue by yangxingrui** [MarcusNerva/HMN#14]
首先感谢您分享团队的工作成果！
我的工作需要使用Faster-RCNN预训练模型，如果您能分享使用MSR-VTT和MSVD数据集训练的Faster-RCNN，我将不胜感激！
或者您将用于目标检测的MSR-VTT和MSVD分享出来。

**Comment by MarcusNerva** [comment]
> 首先感谢您分享团队的工作成果！ 我的工作需要使用Faster-RCNN预训练模型，如果您能分享使用MSR-VTT和MSVD数据集训练的Faster-RCNN，我将不胜感激！ 或者您将用于目标检测的MSR-VTT和MSVD分享出来。

check this: https://github.com/shilrley6/Faster-R-CNN-with-model-pretrained-on-Visual-Genome

**Comment by syl0107** [comment]
请问这个Faster-RCNN的模型您跑通了吗？我在编译的时候出了很多问题，如果您有完整的Faster-rcnn的代码，您可以分享给我一份吗？非常感谢您！我的邮箱2725334453@qq.com @yangxingrui

**Comment by syl0107** [comment]
> 首先感谢您分享团队的工作成果！ 我的工作需要使用Faster-RCNN预训练模型，如果您能分享使用MSR-VTT和MSVD数据集训练的Faster-RCNN，我将不胜感激！ 或者您将用于目标检测的MSR-VTT和MSVD分享出来。

请问这个Faster-RCNN的模型您跑通了吗？我在编译的时候出了很多问题，如果您有完整的Faster-RCNN代码，您可以分享给我一份吗？非常感谢您！我的邮箱是2725334453@qq.com

**Comment by tjumc** [comment]
您好，请问您能否把作者分享的预处理文件发给我一份？因为作者提供的链接已经失效了，我的邮箱是：chongma@email.ncu.edu.cn

**Comment by tjumc** [comment]
> > 首先感谢您分享团队的工作成果！ 我的工作需要使用Faster-RCNN预训练模型，如果您能分享使用MSR-VTT和MSVD数据集训练的Faster-RCNN，我将不胜感激！ 或者您将用于目标检测的MSR-VTT和MSVD分享出来。
> 
> 请问这个Faster-RCNN的模型您跑通了吗？我在编译的时候出了很多问题，如果您有完整的Faster-RCNN代码，您可以分享给我一份吗？非常感谢您！我的邮箱是[2725334453@qq.com](mailto:2725334453@qq.com)

您好，请问您能否把作者分享的预处理文件发给我一份？因为作者提供的链接已经失效了，我的邮箱是：chongma@email.ncu.edu.cn

**Comment by syl0107** [comment]
issue里作者提供的那个链接我记得当时编译源码的时候是有问题的，可能是因为我的电脑问题，您可以试一下。另外附上我当时参考的FasterRCnn源码，如果您有需要的话可以适当修改参考使用。（GitHub - bubbliiiing/faster-rcnn-pytorch: 这是一个faster-rcnn的pytorch实现的库，可以利用voc数据集格式的数据进行训练。）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MarcusNerva/HMN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月25日(星期三) 下午5:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MarcusNerva/HMN] 提取特征的Faster-RCNN可以分享出来吗 (Issue #14)





   
首先感谢您分享团队的工作成果！ 我的工作需要使用Faster-RCNN预训练模型，如果您能分享使用MSR-VTT和MSVD数据集训练的Faster-RCNN，我将不胜感激！ 或者您将用于目标检测的MSR-VTT和MSVD分享出来。
  
***@***.***
  
***@***.***

**Comment by tjumc** [comment]
> issue里作者提供的那个链接我记得当时编译源码的时候是有问题的，可能是因为我的电脑问题，您可以试一下。另外附上我当时参考的FasterRCnn源码，如果您有需要的话可以适当修改参考使用。（GitHub - bubbliiiing/faster-rcnn-pytorch: 这是一个faster-rcnn的pytorch实现的库，可以利用voc数据集格式的数据进行训练。）
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MarcusNerva/HMN" ***@***.***&gt;; 发送时间:&nbsp;2024年12月25日(星期三) 下午5:50 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [MarcusNerva/HMN] 提取特征的Faster-RCNN可以分享出来吗 (Issue #14) 首先感谢您分享团队的工作成果！ 我的工作需要使用Faster-RCNN预训练模型，如果您能分享使用MSR-VTT和MSVD数据集训练的Faster-RCNN，我将不胜感激！ 或者您将用于目标检测的MSR-VTT和MSVD分享出来。 ***@***.*** ***@***.*** — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

感谢您的回复，我想要的是MSVD、MSRVTT的视觉特征文件，因为作者提供的云链接已经失效了，不过我已经找到了。
