### ISSUE TITLE
The Links of Datasets  and Pretrained Model Are Invalid.

### ISSUE THREAD

**Issue by Y-JIE-CREATOR** [MarcusNerva/HMN#15]
Dear Marcus:
    I have found that The Links of the Datasets and Pretrained Model provided on the Readme file are Invalid. So can you update it?
Thank you!

**Comment by MarcusNerva** [comment]
> Dear Marcus: I have found that The Links of the Datasets and Pretrained Model provided on the Readme file are Invalid. So can you update it? Thank you!

Check #3
