### ISSUE TITLE
不好意思 ，想请教一下 transformer.py 当中 normlization 放前或放后 具体的区别在哪里？或者说效果上会有影响吗？谢谢

### ISSUE THREAD

**Issue by xyc0833** [MarcusNerva/HMN#18]
transformer.py当中 有看到你的 forward函数分为两种情况。如图
![image](https://user-images.githubusercontent.com/57979311/210070945-8b1fd224-6925-4eee-9ee3-1846c17c9318.png)
forward_post 函数 具体实现上 正常的对应了DETR这篇论文 先做多头注意力再做 add&norm 
![image](https://user-images.githubusercontent.com/57979311/210071290-670eec47-46bd-4d00-8c55-de2ba4c26196.png)
但是在 forward_pre 函数中 为什么先做 norm 再做多头注意力？这样做的好处是什么？
![image](https://user-images.githubusercontent.com/57979311/210071388-8c76d35e-4a1c-4ea3-bc87-52ce29d5ded2.png)

**Comment by MarcusNerva** [comment]
具体本人没有做过实验，至于放在前放在后其实也是一件很玄学的事情，没有什么特别令人信服的道理
