### ISSUE TITLE
Unable to install requirements 

### ISSUE THREAD

**Issue by rumpfg** [MarcusNerva/HMN#2]
Hi,

I am unable to install many packages in requirements.txt as these contain files at your local PC. How can I install requirements and run this model?

**Comment by rumpfg** [comment]
Also when the pre-trained model will be available?

**Comment by MarcusNerva** [comment]
> Hi,
> 
> I am unable to install many packages in requirements.txt as these contain files at your local PC. How can I install requirements and run this model?

I have removed requirements.txt in my repo. Just using Pytorch1.4 will be fine.

**Comment by MarcusNerva** [comment]
> Also when the pre-trained model will be available?

Pretrained model have been uploaded.
