### ISSUE TITLE
想请教一下例如MSVD_inceptionresnetv2_test.hdf5文件，是将MSVD数据集中的测试集的每个视频的每一帧通过inceptionresnetv2网络得到的结果组合而成的吗？谢谢

### ISSUE THREAD

**Issue by BradenJoson** [MarcusNerva/HMN#21]

**Comment by BradenJoson** [comment]
是否有具体的代码吗？麻烦了

**Comment by xyc0833** [comment]
具体是不是每一帧我不知道  但大致流程应该是的   他有个split data的代码  然后有三个pkl文件 把对应的每个视频整合成三个h5文件   xxx_train.h5  xxx_val.h5  xxx_test.h5

**Comment by tjumc** [comment]
您好，请问您能否把作者分享的预处理文件发给我一份？因为作者提供的链接已经失效了，我的邮箱是：chongma@email.ncu.edu.cn
