### ISSUE TITLE
what the computer setting did you for training? such as CPU,memory and GPU memory size

### ISSUE THREAD

**Issue by Ri-Bai** [MarcusNerva/HMN#23]
this project too large to training for me in GPU3070 computer?
what's wrong for me and my computer will die when I try to train it.

**Comment by panzeyu2013** [comment]
The paper said they use 2080ti to train

**Comment by Ri-Bai** [comment]
> The paper said they use 2080ti to train

Thanks for your reply.
 ![image](https://user-images.githubusercontent.com/74802021/230574598-df6ba0dd-5a38-4460-8415-54747c26ce6c.png)
this is  my computer information. I just try to train this model with the guidance of readme file. but the memory of computer is full rapidly and lead to computer die finally.

**Comment by xyc0833** [comment]
MSR-VTT的话 至少要40G的内存才能跑得动  你需要找一个四卡的服务器 塔式或机架式  比方说四卡服务器有250G内存  然后 选其中一张2080TI去跑  这能才能保证模型能够训练
