### ISSUE TITLE
The Links of Datasets Are Invalid

### ISSUE THREAD

**Issue by TreezzZ** [MarcusNerva/HMN#3]
Hi,

Thanks for your great work!

The download links of datasets provided by README are invalid. Could you update it? Thank you!

**Comment by MarcusNerva** [comment]
> Hi,
> 
> Thanks for your great work!
> 
> The download links of datasets provided by README are invalid. Could you update it? Thank you!

Datasets are uploaded.

**Comment by syl0107** [comment]
> Hi,
> 
> Thanks for your great work!
> 
> The download links of datasets provided by README are invalid. Could you update it? Thank you!

Have you already downloaded the datasets and the pretrained model? If yes, could you share a link to get it?
