### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/MSVD/MSVD_splits/MSVD_train_list.pkl'

### ISSUE THREAD

**Issue by adeljalalyousif** [MarcusNerva/HMN#4]
Really great job, but how can I get the  _MSVD_splits_ files : **MSVD_test_list.pkl        MSVD_train_list.pkl   
          MSVD_valid_list.pkl**
I get this error while running **main.py**
and the **(split_data.py)** is not working because the data files are not available:
parser = argparse.ArgumentParser()
    parser.add_argument('--dataset_name', type=str, default='-1', help='dataset name (MSVD | MSRVTT)')
    parser.add_argument('--split_dir', type=str, default='-1', help='dir contains split_list')
    parser.add_argument('--data_path', type=str, default='-1', help='the path of unsplited data')
    parser.add_argument('--data_name', type=str, default='-1', help='name of unsplited data')
    parser.add_argument('--target_dir', type=str, default='-1', help='where do you want to place your data')
    parser.add_argument('--split_objects', action='store_true')

Thank you so much...

**Comment by MarcusNerva** [comment]
Problem solved, splits.pkl have been uploaded. Please check again.

**Comment by adeljalalyousif** [comment]
Thank you so much for your reply.
 I need your advice please. I am a PhD student working on real-time video captioning, Which one is faster to inference (CNN + LSTM) or (CNN + Transformer) or something else?
Can you provide me with the inference file please , ajalal289@gmail.com. thanks again
