### ISSUE TITLE
The code seems to be missing some parameter settings

### ISSUE THREAD

**Issue by zzzzfly** [MarcusNerva/HMN#5]
The class of TrainingConfigs has no attribute 'weight_decay'
Details are as follows：
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    model = train_fn(cfgs, cfgs.model_name, model, hungary_matcher, train_loader, valid_loader, device)
  File "/data/dataset/zfy_HMN_code/HMN/train.py", line 28, in train_fn
    optimizer = optim.Adam(model.parameters(), lr=cfgs.train.learning_rate, weight_decay=cfgs.train.weight_decay)
AttributeError: 'TrainingConfigs' object has no attribute 'weight_decay'

**Comment by adeljalalyousif** [comment]
Just delete (weight_decay=cfgs.train.weight_decay) from  optimizer.
