### ISSUE TITLE
Some issue to modify the code

### ISSUE THREAD

**Issue by Chenfeng1271** [MarcusNerva/HMN#6]
Hi, thank you for your work. When I implement this code, I meet several problems, mainly from parameter setting. For example,  --language_dir_name, data/MSVD/language/vid2fillmask_MSVD.pkl in data file, missing weight_decay in cfg.train.

**Comment by MarcusNerva** [comment]
> Hi, thank you for your work. When I implement this code, I meet several problems, mainly from parameter setting. For example, --language_dir_name, data/MSVD/language/vid2fillmask_MSVD.pkl in data file, missing weight_decay in cfg.train.

For the first problem, you may solve it by renaming the file.
For the second one, I have updated my repo to solve it, please check again.
