### ISSUE TITLE
coco-caption

### ISSUE THREAD

**Issue by fsh2017** [MarcusNerva/HMN#7]
Thank you for open-source your work, I have had the following issues with testing, I was wondering if this relates to the different COCO_caption implementations, and the specific Coco_caption link you are using
![image](https://user-images.githubusercontent.com/45693321/192514450-4698f2dc-2cbc-4086-8cc3-2d41b0bf0772.png)

**Comment by MarcusNerva** [comment]
> Thank you for open-source your work, I have had the following issues with testing, I was wondering if this relates to the different COCO_caption implementations, and the specific Coco_caption link you are using ![image](https://user-images.githubusercontent.com/45693321/192514450-4698f2dc-2cbc-4086-8cc3-2d41b0bf0772.png)

Well, this bug is cause by the coco caption auto metrics. I met these kinds of problems before, and solve it by googling. 
Try [this](https://github.com/Maluuba/nlg-eval/issues/32) to see if it can solve your problem.

**Comment by liyaowei-stu** [comment]
I still haven't solved it. Can you share some insights on how to operate it? Thank you so much!

**Comment by myccver** [comment]
> I still haven't solved it. Can you share some insights on how to operate it? Thank you so much!

这应该与你的coco-caption版本有关系，在/coco_caption/pycocoevalcap/meteor里做如下修改：
<img width="521" alt="1668527465907" src="https://user-images.githubusercontent.com/66241749/201964411-0da4754d-5e3e-4ffa-bba3-09dd759ddb28.png">
加上标记的代码后应该就可以了：
score_line = score_line.replace('\n', '').replace('\r', '')
希望对你有所帮助。

**Comment by xyc0833** [comment]
没有用啊  应该还是要安装java吧

**Comment by xyc0833** [comment]
> 这应该与你的coco-caption版本有关系，在/coco_caption/pycocoevalcap/meteor里做如下修改：

感恩感谢 It is work  thank
