### ISSUE TITLE
coco-caption

### ISSUE THREAD

**Issue by Longshunhong** [MarcusNerva/HMN#8]
I have a problem with evaluation indicators at runtime. Who can help me solve it. The problem is

Error: specify SCORE or EVAL or SING ||| Error: specify SCORE or EVAL or SING ||| 4.0 7.0 2.0 4.0 2.0 2.0 2.0 2.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 4.0 4.0 ||| ....

**Comment by tjumc** [comment]
My dear friend，How did you solve this problem：
![image](https://user-images.githubusercontent.com/67730345/194567995-4ff0d3ef-b34b-48d9-87ea-b665d7fc918b.png)

**Comment by Longshunhong** [comment]
> My dear friend，How did you solve this problem： ![image](https://user-images.githubusercontent.com/67730345/194567995-4ff0d3ef-b34b-48d9-87ea-b665d7fc918b.png)

Dear friends, I also encountered this problem, and now I'm trying to get in touch with the author

**Comment by Longshunhong** [comment]
Dear friends, I also encountered this problem, and now I'm trying to get in touch with the author.Have you solved this problem？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MarcusNerva/HMN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月7日(星期五) 晚上9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MarcusNerva/HMN] coco-caption (Issue #8)





 
My dear friend，How did you solve this problem：

**Comment by NCU-MC** [comment]
还没有，上周比较忙没有debug，这周再尝试一下。

**Comment by tjumc** [comment]
> Dear friends, I also encountered this problem, and now I'm trying to get in touch with the author.Have you solved this problem？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MarcusNerva/HMN" ***@***.***&gt;; 发送时间:&nbsp;2022年10月7日(星期五) 晚上9:43 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [MarcusNerva/HMN] coco-caption (Issue #8) My dear friend，How did you solve this problem： — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

还没有，上周事情有点多没有时间debug，这周尝试一下能不能解决。

**Comment by Longshunhong** [comment]
> > Dear friends, I also encountered this problem, and now I'm trying to get in touch with the author.Have you solved this problem？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "MarcusNerva/HMN" _**@**_._**>; 发送时间: 2022年10月7日(星期五) 晚上9:43 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [MarcusNerva/HMN] coco-caption (Issue #8) My dear friend，How did you solve this problem： — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 还没有，上周事情有点多没有时间debug，这周尝试一下能不能解决。

In the training process, the process is always killed. Have you encountered this problem?

**Comment by cayl-crypto** [comment]
If the process is Killed. This means that your computer is not sufficent enough to run this code. I suggest you to implement the code in a machine with high computational power. Like have rtx 3090ti gpu, strong cpu and high speed RAMs with a lot of MBs.

**Comment by myccver** [comment]
> My dear friend，How did you solve this problem： ![image](https://user-images.githubusercontent.com/67730345/194567995-4ff0d3ef-b34b-48d9-87ea-b665d7fc918b.png)

Hi, I meet the same error. The length of prediction and reference is 670, it works when I select slice data of them to calculate meteor_score. Could you share how you solved this problem？

**Comment by NCU-MC** [comment]
在 train.py 文件中，将
` print('=' * 10,'[EPOCH{epoch} iter{it}] :Best Cider is {bs}, Current Cider is {cs}'.format(epoch=epoch, it=i, bs=best_score, cs=cider_score),'=' * 10)`
改为
`print('=' * 10 + '[EPOCH{epoch} iter{it}] :Best Cider is {bs}, Current Cider is {cs}'.format(epoch=epoch, it=i, bs=best_score, cs=cider_score) + '=' * 10)`
试一下看有没有效果？我的已经可以正常运行了

**Comment by tjumc** [comment]
> 

被杀死的情况我也遇到过，查询原因为 "out of memory"，所以如果服务器内存不足或者正在运行的进程过多，都会造成这样的情况。
