### ISSUE TITLE
Problems in the training process

### ISSUE THREAD

**Issue by Longshunhong** [MarcusNerva/HMN#9]
In the training process, the process is always killed. How to solve this problem？

**Comment by cayl-crypto** [comment]
If the process is Killed. This means that your computer is not sufficent enough to run this code. I suggest you to implement the code in a machine with high computational power. Like have rtx 3090ti gpu, strong cpu and high speed RAMs with a lot of MBs. 

> In the training process, the process is always killed. How to solve this problem？
